package com.reelshort.app.ui.format

import com.reelshort.app.data.AppLanguage

internal data class AppStrings(
    val homeTab: String,
    val searchTab: String,
    val accountTab: String,
    val loginScreen: String,
    val detailScreen: String,
    val playerScreen: String,
    val favoritesScreen: String,
    val searchTitle: String,
    val searchSubtitle: String,
    val searchHint: String,
    val searchAction: String,
    val searchTagsTitle: String,
    val searchHeroEyebrow: String,
    val searchResultTitle: String,
    val searchResultCountSuffix: String,
    val searchEmptyTitle: String,
    val searchInitialHint: String,
    val searchEmpty: String,
    val languageTitle: String,
    val languageSubtitle: String,
    val loadingDialogTitle: String,
    val homeHeaderTitle: String,
    val homeHeaderSubtitleSuffix: String,
    val favoritesHeaderTitle: String,
    val favoritesHeaderSubtitleSuffix: String,
    val diagnosticsTitle: String,
    val diagnosticsExpand: String,
    val diagnosticsCollapse: String,
    val diagnosticsRefresh: String,
    val diagnosticsApiMissing: String,
    val diagnosticsUnknownLabel: String,
    val diagnosticsUnknownMessage: String,
    val diagnosticsUpLabel: String,
    val diagnosticsUpMessagePrefix: String,
    val diagnosticsDownLabel: String,
    val diagnosticsDownMessagePrefix: String,
    val homeEmptyTitle: String,
    val homeEmptyMessage: String,
    val homeEmptyAction: String,
    val favoritesEmptyTitle: String,
    val favoritesEmptyMessage: String,
    val searchDefaultEmptyTitle: String,
    val searchDefaultEmptyMessage: String,
    val searchNoResultsTitle: String,
    val searchNoResultsMessagePrefix: String,
    val searchNoResultsMessageSuffix: String,
    val searchRetryAction: String,
    val detailEmptyTitle: String,
    val detailEmptyMessage: String,
    val detailEmptyAction: String,
    val detailUnavailableTitle: String,
    val detailUnavailableMessagePrefix: String,
    val detailUnavailableMessageSuffix: String,
    val detailUnavailableAction: String,
    val accountFavoritesTitle: String,
    val accountPointsTitle: String,
    val accountWatchHistoryTitle: String,
    val accountPointRecordsTitle: String,
    val accountOrdersTitle: String,
    val accountWalletTitle: String,
    val accountWithdrawTitle: String,
    val accountTransferTitle: String,
    val accountTransferRecordsTitle: String,
    val accountChangePasswordTitle: String,
    val accountBankCardTitle: String,
    val accountBankCardSubtitle: String,
    val authContinue: String,
    val accountWithdrawalsTitle: String,
    val accountDiagnosticsTitle: String,
    val accountSignOutTitle: String,
    val accountGuestSignIn: String,
    val accountGuestRegister: String,
    val accountGuestSignInSubtitle: String,
    val accountGuestRegisterSubtitle: String,
    val accountFavoritesSubtitle: String,
    val accountViewAction: String,
    val accountPointsSuffix: String,
    val accountRecentCountPrefix: String,
    val accountRecordsSuffix: String,
    val accountOrdersReserved: String,
    val accountOrdersRecentSuffix: String,
    val accountRecentWatchTitle: String,
    val accountRecentWatchSubtitle: String,
    val accountSelectedLanguage: String,
    val accountUserFallback: String,
    val accountGuestUser: String,
    val accountLoggedInStatus: String,
    val accountGuestStatus: String,
    val accountPointsPillPrefix: String,
    val accountGuestPill: String,
    val accountLoggedInRewardHint: String,
    val accountGuestRewardHint: String,
    val accountSignOutSubtitle: String,
    val accountSignInSuccessHint: String,
    val authLoginTitle: String,
    val authLoginSubtitle: String,
    val authRegisterTitle: String,
    val authRegisterSubtitle: String,
    val authBottomSheetPlaybackSubtitle: String,
    val authBottomSheetAccountSubtitle: String,
    val authBrandSubtitle: String,
    val authClose: String,
    val authUsernameLabel: String,
    val authPasswordLabel: String,
    val authLoginLoading: String,
    val authLoginAction: String,
    val authLoginSecondary: String,
    val authRegisterAction: String,
    val authRegisterSecondary: String,
    val authCaptchaLabel: String,
    val authCaptchaAnswerLabel: String,
    val authCaptchaRefresh: String,
    val authCaptchaLoading: String,
    val authConfirmPasswordLabel: String,
    val authPromptPlayback: String,
    val authPromptAccount: String,
    val rememberPassword: String,
    val playerEpisodePrefix: String,
    val playerEpisodeUnit: String,
    val playerPlayAction: String,
    val playerLoadingPrefix: String,
    val playerLoadingSuffix: String,
    val playerEpisodeSelectorPrefix: String,
    val playerEpisodeSelectorCompleted: String,
    val playerEpisodeSelectorTotalPrefix: String,
    val playerEpisodeSelectorTotalSuffix: String,
    val playerRefreshAction: String,
    val playerRetryAction: String,
    val playerNextEpisodeAction: String,
    val playerBackAction: String,
    val playerRewardError: String,
    val playerVideoError: String,
    val playerFavoriteLabel: String,
    val playerCurrentEpisodePrefix: String,
    val playerEpisodeStatusCurrent: String,
    val playerEpisodeStatusWatched: String,
    val playerExpandEpisodes: String,
    val playerClose: String,
    val playerCommentsTitlePrefix: String,
    val playerCommentsEmpty: String,
    val playerCommentPlaceholder: String,
    val playerSend: String,
    val playerCommentUnit: String,
    val listEpisodePrefix: String,
    val listPointsChangeFallback: String,
    val listPointRecordSubtitle: String,
    val listCurrencySymbol: String,
    val listPointsLabel: String,
    val accountFrozenAvailableLabel: String,
    val accountWalletNoBound: String,
    val accountWalletAddressLabel: String,
    val accountWalletUnbindCode: String,
    val accountWalletBindAction: String,
    val accountWalletReplaceAction: String,
    val accountWalletUnbindAction: String,
    val accountVipStatusActive: String,
    val accountVipStatusInactive: String,
    val accountVipExpiryPrefix: String,
    val accountVipUnlockAction: String,
    val accountVipPriceSuffix: String,
    val accountVipNoOrders: String,
    val vipDialogTitle: String,
    val vipActiveLabel: String,
    val vipExpiryLabel: String,
    val vipPayTitle: String,
    val vipPayAmount: String,
    val vipPayAddress: String,
    val vipPayCopy: String,
    val vipPayOrderNo: String,
    val vipPayStatusPending: String,
    val vipPayStatusConfirmed: String,
    val vipPayStatusRejected: String,
    val vipPayHint: String,
    val vipRecordsTitle: String,
    val accountWithdrawAvailableLabel: String,
    val accountWithdrawMinimumLabel: String,
    val accountWithdrawRateLabel: String,
    val accountWithdrawWalletRequired: String,
    val accountWithdrawPointAmountLabel: String,
    val accountWithdrawSubmitAction: String,
    val accountTransferHelp: String,
    val accountTransferRecipientLabel: String,
    val accountTransferPointsLabel: String,
    val accountTransferInLabel: String,
    val accountTransferOutLabel: String,
    val accountPasswordNewLabel: String,
    val accountBankCardUnsupported: String,
    val accountBankCardHolderLabel: String,
    val accountBankCardNumberLabel: String,
    val commonNotSupported: String,
    val posterEpisodeUnit: String,
    val bookRowFallbackSuffix: String,
    val bookRowViewAction: String,
    val geoBlockedTitle: String,
    val geoBlockedMessage: String,
)

internal fun strings(language: AppLanguage): AppStrings =
    when (language) {
        AppLanguage.ENGLISH -> AppStrings(
            homeTab = "Home",
            searchTab = "Discover",
            accountTab = "Me",
            loginScreen = "Sign in",
            detailScreen = "Details",
            playerScreen = "Player",
            favoritesScreen = "Favorites",
            searchTitle = "Discover",
            searchSubtitle = "Start with a trope, role, or keyword.",
            searchHint = "Search romance, CEO, revenge...",
            searchAction = "Search",
            searchTagsTitle = "Popular lanes",
            searchHeroEyebrow = "Curated discovery",
            searchResultTitle = "Results",
            searchResultCountSuffix = "dramas",
            searchEmptyTitle = "Find your next drama",
            searchInitialHint = "Choose a preset tag or search by title.",
            searchEmpty = "No dramas matched this search.",
            languageTitle = "Language",
            languageSubtitle = "English",
            loadingDialogTitle = "Loading",
            homeHeaderTitle = "Today's picks",
            homeHeaderSubtitleSuffix = "dramas selected for you",
            favoritesHeaderTitle = "Favorites",
            favoritesHeaderSubtitleSuffix = "saved dramas",
            diagnosticsTitle = "Diagnostics",
            diagnosticsExpand = "View",
            diagnosticsCollapse = "Collapse",
            diagnosticsRefresh = "Refresh diagnostics",
            diagnosticsApiMissing = "API base URL is not configured",
            diagnosticsUnknownLabel = "Unchecked",
            diagnosticsUnknownMessage = "Tap refresh to verify the emulator can reach the Spring Boot API.",
            diagnosticsUpLabel = "Connected",
            diagnosticsUpMessagePrefix = "Backend ",
            diagnosticsDownLabel = "Unavailable",
            diagnosticsDownMessagePrefix = "Backend health is ",
            homeEmptyTitle = "No picks right now",
            homeEmptyMessage = "The provider did not return recommendations yet. Try search instead.",
            homeEmptyAction = "Go to search",
            favoritesEmptyTitle = "No favorites yet",
            favoritesEmptyMessage = "Tap favorite on the player and saved dramas will show up here.",
            searchDefaultEmptyTitle = "Discover dramas",
            searchDefaultEmptyMessage = "Search by title, role, or keyword to find your next drama.",
            searchNoResultsTitle = "No matching dramas",
            searchNoResultsMessagePrefix = "Nothing matched “",
            searchNoResultsMessageSuffix = "”. Try another keyword.",
            searchRetryAction = "Search again",
            detailEmptyTitle = "Pick a drama first",
            detailEmptyMessage = "Open a title from Home or Discover to see its episodes here.",
            detailEmptyAction = "Back to home",
            detailUnavailableTitle = "Episodes unavailable",
            detailUnavailableMessagePrefix = "“",
            detailUnavailableMessageSuffix = "” has no playable episodes right now. Try again later or choose another title.",
            detailUnavailableAction = "Choose another drama",
            accountFavoritesTitle = "Favorites",
            accountPointsTitle = "Points",
            accountWatchHistoryTitle = "Watch history",
            accountPointRecordsTitle = "Point records",
            accountOrdersTitle = "VIP Orders",
            accountWalletTitle = "Cold wallet",
            accountWithdrawTitle = "Withdraw",
            accountTransferTitle = "Transfer points",
            accountTransferRecordsTitle = "Transfer records",
            accountChangePasswordTitle = "Change password",
            accountBankCardTitle = "Bank card",
            accountBankCardSubtitle = "Credit card",
            authContinue = "Continue",
            accountWithdrawalsTitle = "Withdrawals",
            accountDiagnosticsTitle = "Diagnostics",
            accountSignOutTitle = "Sign out",
            accountGuestSignIn = "Sign in",
            accountGuestRegister = "Create account",
            accountGuestSignInSubtitle = "Sign in to watch dramas and earn rewards",
            accountGuestRegisterSubtitle = "Create an account to keep your progress",
            accountFavoritesSubtitle = "Saved dramas",
            accountViewAction = "View",
            accountPointsSuffix = " pts",
            accountRecentCountPrefix = "Recent ",
            accountRecordsSuffix = " items",
            accountOrdersReserved = "No VIP orders yet",
            accountOrdersRecentSuffix = " orders",
            accountRecentWatchTitle = "Continue watching",
            accountRecentWatchSubtitle = "Pick up from your last episode",
            accountSelectedLanguage = "Selected",
            accountUserFallback = "ShortLink user",
            accountGuestUser = "Guest",
            accountLoggedInStatus = "Signed in · ShortLink",
            accountGuestStatus = "Sign in to keep watch progress and rewards",
            accountPointsPillPrefix = "Points ",
            accountGuestPill = "Guest mode",
            accountLoggedInRewardHint = "Keep watching to earn rewards",
            accountGuestRewardHint = "Browse Home and Discover before signing in",
            accountSignOutSubtitle = "Sign out of this account",
            accountSignInSuccessHint = "Signed in",
            authLoginTitle = "Welcome back",
            authLoginSubtitle = "Sign in with your username to continue.",
            authRegisterTitle = "Create your account",
            authRegisterSubtitle = "Pick a username, set a password, and solve the captcha.",
            authBottomSheetPlaybackSubtitle = "Playback, rewards, and account data require sign in.",
            authBottomSheetAccountSubtitle = "Sign in to view points, watch history, and orders.",
            authBrandSubtitle = "Aggregated short drama player",
            authClose = "Close",
            authUsernameLabel = "Username",
            authPasswordLabel = "Password",
            authLoginLoading = "Signing in",
            authLoginAction = "Sign in",
            authLoginSecondary = "Already have access? Sign in",
            authRegisterAction = "Create account",
            authRegisterSecondary = "New here? Create account",
            authCaptchaLabel = "Captcha",
            authCaptchaAnswerLabel = "Captcha answer",
            authCaptchaRefresh = "Refresh captcha",
            authCaptchaLoading = "Loading captcha",
            authConfirmPasswordLabel = "Confirm password",
            authPromptPlayback = "Sign in to keep watching",
            authPromptAccount = "Sign in to view your account",
            rememberPassword = "Remember password",
            playerEpisodePrefix = "EP ",
            playerEpisodeUnit = "",
            playerPlayAction = "Play",
            playerLoadingPrefix = "Loading ",
            playerLoadingSuffix = "...",
            playerEpisodeSelectorPrefix = "Episodes",
            playerEpisodeSelectorCompleted = "Completed",
            playerEpisodeSelectorTotalPrefix = "Total ",
            playerEpisodeSelectorTotalSuffix = "",
            playerRefreshAction = "Refresh stream",
            playerRetryAction = "Retry",
            playerNextEpisodeAction = "Next episode",
            playerBackAction = "Back",
            playerRewardError = "Reward claim failed. You can keep watching.",
            playerVideoError = "Video failed to load. Please try again later.",
            playerFavoriteLabel = "Favorite",
            playerCurrentEpisodePrefix = "Current ",
            playerEpisodeStatusCurrent = "Current",
            playerEpisodeStatusWatched = "Watched",
            playerExpandEpisodes = "Open episode list",
            playerClose = "Close",
            playerCommentsTitlePrefix = "Comments ",
            playerCommentsEmpty = "No comments yet. Be the first one here.",
            playerCommentPlaceholder = "Write a comment…",
            playerSend = "Send",
            playerCommentUnit = "comments",
            listEpisodePrefix = "Episode ",
            listPointsChangeFallback = "Point update",
            listPointRecordSubtitle = "Point record",
            listCurrencySymbol = "$",
            listPointsLabel = "pts",
            accountFrozenAvailableLabel = "Frozen / available",
            accountWalletNoBound = "No wallet bound",
            accountWalletAddressLabel = "TRC20 wallet address",
            accountWalletUnbindCode = "Unbind code",
            accountWalletBindAction = "Bind wallet",
            accountWalletReplaceAction = "Replace wallet",
            accountWalletUnbindAction = "Unbind",
            accountVipStatusActive = "VIP active",
            accountVipStatusInactive = "VIP not active",
            accountVipExpiryPrefix = "Expires ",
            accountVipUnlockAction = "Unlock VIP",
            accountVipPriceSuffix = " USDT / 30 days",
            accountVipNoOrders = "No VIP orders yet.",
            vipDialogTitle = "VIP Membership",
            vipActiveLabel = "Status: Active",
            vipExpiryLabel = "Expires: ",
            vipPayTitle = "VIP Payment",
            vipPayAmount = "Amount: ",
            vipPayAddress = "Send USDT (TRC20) to:",
            vipPayCopy = "Copy",
            vipPayOrderNo = "Order: ",
            vipPayStatusPending = "Awaiting confirmation",
            vipPayStatusConfirmed = "Confirmed",
            vipPayStatusRejected = "Rejected",
            vipPayHint = "After sending USDT, admin will confirm shortly. VIP activates instantly after confirmation.",
            vipRecordsTitle = "VIP Orders",
            accountWithdrawAvailableLabel = "Available",
            accountWithdrawMinimumLabel = "Min",
            accountWithdrawRateLabel = "1 pt",
            accountWithdrawWalletRequired = "Bind a cold wallet before withdrawal.",
            accountWithdrawPointAmountLabel = "Point amount",
            accountWithdrawSubmitAction = "Submit withdrawal",
            accountTransferHelp = "Use the recipient's username, for example alice.",
            accountTransferRecipientLabel = "Recipient account",
            accountTransferPointsLabel = "Points",
            accountTransferInLabel = "Received",
            accountTransferOutLabel = "Sent",
            accountPasswordNewLabel = "New password",
            accountBankCardUnsupported = "Bank card withdrawal is not supported. This entry is reserved.",
            accountBankCardHolderLabel = "Holder name",
            accountBankCardNumberLabel = "Card number",
            commonNotSupported = "Not supported",
            posterEpisodeUnit = " eps",
            bookRowFallbackSuffix = " episodes",
            bookRowViewAction = "View",
            geoBlockedTitle = "Service Unavailable",
            geoBlockedMessage = "ShortLink is not available in your region. Please use a VPN or try again from a different network.",
        )
    }

internal fun searchDiscoveryTags(language: AppLanguage): List<String> =
    searchDiscoveryGroups(language).flatMap { it.tags }

internal data class SearchDiscoveryGroup(
    val title: String,
    val tags: List<String>,
)

internal fun searchDiscoveryGroups(language: AppLanguage): List<SearchDiscoveryGroup> =
    when (language) {
        AppLanguage.ENGLISH -> listOf(
            SearchDiscoveryGroup("Story moods", listOf("Love", "Revenge", "Secret", "Family")),
            SearchDiscoveryGroup("Power roles", listOf("Billionaire", "CEO", "Boss", "Queen", "Doctor")),
            SearchDiscoveryGroup("Relationships", listOf("Marriage", "Contract", "Pregnant")),
            SearchDiscoveryGroup("Fantasy heat", listOf("Mafia", "Werewolf", "Alpha", "Luna")),
        )
    }

internal fun searchShowsResultsFirst(query: String, resultCount: Int): Boolean =
    query.isNotBlank() || resultCount > 0
