package com.reelshort.app.ui.format

import com.reelshort.app.data.AppLanguage

internal data class AppStrings(
    val homeTab: String,
    val searchTab: String,
    val accountTab: String,
    val loginScreen: String,
    val detailScreen: String,
    val playerScreen: String,
    val favoritesScreen: String,
    val searchTitle: String,
    val searchSubtitle: String,
    val searchHint: String,
    val searchAction: String,
    val searchTagsTitle: String,
    val searchHeroEyebrow: String,
    val searchResultTitle: String,
    val searchResultCountSuffix: String,
    val searchEmptyTitle: String,
    val searchInitialHint: String,
    val searchEmpty: String,
    val languageTitle: String,
    val languageSubtitle: String,
    val loadingDialogTitle: String,
    val homeHeaderTitle: String,
    val homeHeaderSubtitleSuffix: String,
    val favoritesHeaderTitle: String,
    val favoritesHeaderSubtitleSuffix: String,
    val diagnosticsTitle: String,
    val diagnosticsExpand: String,
    val diagnosticsCollapse: String,
    val diagnosticsRefresh: String,
    val diagnosticsApiMissing: String,
    val diagnosticsUnknownLabel: String,
    val diagnosticsUnknownMessage: String,
    val diagnosticsUpLabel: String,
    val diagnosticsUpMessagePrefix: String,
    val diagnosticsDownLabel: String,
    val diagnosticsDownMessagePrefix: String,
    val homeEmptyTitle: String,
    val homeEmptyMessage: String,
    val homeEmptyAction: String,
    val favoritesEmptyTitle: String,
    val favoritesEmptyMessage: String,
    val searchDefaultEmptyTitle: String,
    val searchDefaultEmptyMessage: String,
    val searchNoResultsTitle: String,
    val searchNoResultsMessagePrefix: String,
    val searchNoResultsMessageSuffix: String,
    val searchRetryAction: String,
    val detailEmptyTitle: String,
    val detailEmptyMessage: String,
    val detailEmptyAction: String,
    val detailUnavailableTitle: String,
    val detailUnavailableMessagePrefix: String,
    val detailUnavailableMessageSuffix: String,
    val detailUnavailableAction: String,
    val accountFavoritesTitle: String,
    val accountPointsTitle: String,
    val accountWatchHistoryTitle: String,
    val accountPointRecordsTitle: String,
    val accountOrdersTitle: String,
    val accountWalletTitle: String,
    val accountWithdrawTitle: String,
    val accountTransferTitle: String,
    val accountTransferRecordsTitle: String,
    val accountChangePasswordTitle: String,
    val accountBankCardTitle: String,
    val accountWithdrawalsTitle: String,
    val accountDiagnosticsTitle: String,
    val accountSignOutTitle: String,
    val accountGuestSignIn: String,
    val accountGuestRegister: String,
    val accountGuestSignInSubtitle: String,
    val accountGuestRegisterSubtitle: String,
    val accountFavoritesSubtitle: String,
    val accountViewAction: String,
    val accountPointsSuffix: String,
    val accountRecentCountPrefix: String,
    val accountRecordsSuffix: String,
    val accountOrdersReserved: String,
    val accountOrdersRecentSuffix: String,
    val accountRecentWatchTitle: String,
    val accountRecentWatchSubtitle: String,
    val accountSelectedLanguage: String,
    val accountUserFallback: String,
    val accountGuestUser: String,
    val accountLoggedInStatus: String,
    val accountGuestStatus: String,
    val accountPointsPillPrefix: String,
    val accountGuestPill: String,
    val accountLoggedInRewardHint: String,
    val accountGuestRewardHint: String,
    val accountSignOutSubtitle: String,
    val accountSignInSuccessHint: String,
    val authLoginTitle: String,
    val authLoginSubtitle: String,
    val authRegisterTitle: String,
    val authRegisterSubtitle: String,
    val authBottomSheetPlaybackSubtitle: String,
    val authBottomSheetAccountSubtitle: String,
    val authBrandSubtitle: String,
    val authClose: String,
    val authUsernameLabel: String,
    val authPasswordLabel: String,
    val authLoginLoading: String,
    val authLoginAction: String,
    val authLoginSecondary: String,
    val authRegisterAction: String,
    val authRegisterSecondary: String,
    val authSendCode: String,
    val authVerificationCodeLabel: String,
    val authPromptPlayback: String,
    val authPromptAccount: String,
    val rememberPassword: String,
    val playerEpisodePrefix: String,
    val playerEpisodeUnit: String,
    val playerPlayAction: String,
    val playerLoadingPrefix: String,
    val playerLoadingSuffix: String,
    val playerEpisodeSelectorPrefix: String,
    val playerEpisodeSelectorCompleted: String,
    val playerEpisodeSelectorTotalPrefix: String,
    val playerEpisodeSelectorTotalSuffix: String,
    val playerRefreshAction: String,
    val playerRetryAction: String,
    val playerNextEpisodeAction: String,
    val playerBackAction: String,
    val playerRewardError: String,
    val playerVideoError: String,
    val playerFavoriteLabel: String,
    val playerCurrentEpisodePrefix: String,
    val playerEpisodeStatusCurrent: String,
    val playerEpisodeStatusWatched: String,
    val playerExpandEpisodes: String,
    val playerClose: String,
    val playerCommentsTitlePrefix: String,
    val playerCommentsEmpty: String,
    val playerCommentPlaceholder: String,
    val playerSend: String,
    val playerCommentUnit: String,
    val listEpisodePrefix: String,
    val listPointsChangeFallback: String,
    val listPointRecordSubtitle: String,
    val listCurrencySymbol: String,
    val listPointsLabel: String,
    val accountFrozenAvailableLabel: String,
    val accountWalletNoBound: String,
    val accountWalletAddressLabel: String,
    val accountWalletUnbindCode: String,
    val accountWalletBindAction: String,
    val accountWalletReplaceAction: String,
    val accountWalletUnbindAction: String,
    val accountWithdrawAvailableLabel: String,
    val accountWithdrawMinimumLabel: String,
    val accountWithdrawRateLabel: String,
    val accountWithdrawWalletRequired: String,
    val accountWithdrawPointAmountLabel: String,
    val accountWithdrawSubmitAction: String,
    val accountTransferHelp: String,
    val accountTransferRecipientLabel: String,
    val accountTransferPointsLabel: String,
    val accountTransferInLabel: String,
    val accountTransferOutLabel: String,
    val accountPasswordNewLabel: String,
    val accountBankCardUnsupported: String,
    val accountBankCardHolderLabel: String,
    val accountBankCardNumberLabel: String,
    val commonNotSupported: String,
    val posterEpisodeUnit: String,
    val bookRowFallbackSuffix: String,
    val bookRowViewAction: String,
)

internal fun strings(language: AppLanguage): AppStrings =
    when (language) {
        AppLanguage.ENGLISH -> AppStrings(
            homeTab = "Home",
            searchTab = "Discover",
            accountTab = "Me",
            loginScreen = "Sign in",
            detailScreen = "Details",
            playerScreen = "Player",
            favoritesScreen = "Favorites",
            searchTitle = "Discover",
            searchSubtitle = "Start with a trope, role, or keyword.",
            searchHint = "Search romance, CEO, revenge...",
            searchAction = "Search",
            searchTagsTitle = "Popular lanes",
            searchHeroEyebrow = "Curated discovery",
            searchResultTitle = "Results",
            searchResultCountSuffix = "dramas",
            searchEmptyTitle = "Find your next drama",
            searchInitialHint = "Choose a preset tag or search by title.",
            searchEmpty = "No dramas matched this search.",
            languageTitle = "Language",
            languageSubtitle = "English / 繁體中文",
            loadingDialogTitle = "Loading",
            homeHeaderTitle = "Today's picks",
            homeHeaderSubtitleSuffix = "dramas selected for you",
            favoritesHeaderTitle = "Favorites",
            favoritesHeaderSubtitleSuffix = "saved dramas",
            diagnosticsTitle = "Diagnostics",
            diagnosticsExpand = "View",
            diagnosticsCollapse = "Collapse",
            diagnosticsRefresh = "Refresh diagnostics",
            diagnosticsApiMissing = "API base URL is not configured",
            diagnosticsUnknownLabel = "Unchecked",
            diagnosticsUnknownMessage = "Tap refresh to verify the emulator can reach the Spring Boot API.",
            diagnosticsUpLabel = "Connected",
            diagnosticsUpMessagePrefix = "Backend ",
            diagnosticsDownLabel = "Unavailable",
            diagnosticsDownMessagePrefix = "Backend health is ",
            homeEmptyTitle = "No picks right now",
            homeEmptyMessage = "The provider did not return recommendations yet. Try search instead.",
            homeEmptyAction = "Go to search",
            favoritesEmptyTitle = "No favorites yet",
            favoritesEmptyMessage = "Tap favorite on the player and saved dramas will show up here.",
            searchDefaultEmptyTitle = "Discover dramas",
            searchDefaultEmptyMessage = "Search by title, role, or keyword to find your next drama.",
            searchNoResultsTitle = "No matching dramas",
            searchNoResultsMessagePrefix = "Nothing matched “",
            searchNoResultsMessageSuffix = "”. Try another keyword.",
            searchRetryAction = "Search again",
            detailEmptyTitle = "Pick a drama first",
            detailEmptyMessage = "Open a title from Home or Discover to see its episodes here.",
            detailEmptyAction = "Back to home",
            detailUnavailableTitle = "Episodes unavailable",
            detailUnavailableMessagePrefix = "“",
            detailUnavailableMessageSuffix = "” has no playable episodes right now. Try again later or choose another title.",
            detailUnavailableAction = "Choose another drama",
            accountFavoritesTitle = "Favorites",
            accountPointsTitle = "Points",
            accountWatchHistoryTitle = "Watch history",
            accountPointRecordsTitle = "Point records",
            accountOrdersTitle = "Orders",
            accountWalletTitle = "Cold wallet",
            accountWithdrawTitle = "Withdraw",
            accountTransferTitle = "Transfer points",
            accountTransferRecordsTitle = "Transfer records",
            accountChangePasswordTitle = "Change password",
            accountBankCardTitle = "Bank card",
            accountWithdrawalsTitle = "Withdrawals",
            accountDiagnosticsTitle = "Diagnostics",
            accountSignOutTitle = "Sign out",
            accountGuestSignIn = "Sign in",
            accountGuestRegister = "Create account",
            accountGuestSignInSubtitle = "Sign in to watch dramas and earn rewards",
            accountGuestRegisterSubtitle = "Create an account to keep your progress",
            accountFavoritesSubtitle = "Saved dramas",
            accountViewAction = "View",
            accountPointsSuffix = " pts",
            accountRecentCountPrefix = "Recent ",
            accountRecordsSuffix = " items",
            accountOrdersReserved = "Commercial slot reserved",
            accountOrdersRecentSuffix = " orders",
            accountRecentWatchTitle = "Continue watching",
            accountRecentWatchSubtitle = "Pick up from your last episode",
            accountSelectedLanguage = "Selected",
            accountUserFallback = "ShortLink user",
            accountGuestUser = "Guest",
            accountLoggedInStatus = "Signed in · ShortLink",
            accountGuestStatus = "Sign in to keep watch progress and rewards",
            accountPointsPillPrefix = "Points ",
            accountGuestPill = "Guest mode",
            accountLoggedInRewardHint = "Keep watching to earn rewards",
            accountGuestRewardHint = "Browse Home and Discover before signing in",
            accountSignOutSubtitle = "Sign out of this account",
            accountSignInSuccessHint = "Signed in",
            authLoginTitle = "Welcome back",
            authLoginSubtitle = "Sign in with your phone account to continue.",
            authRegisterTitle = "Create your account",
            authRegisterSubtitle = "Use a non-mainland phone number and enter the 6-digit code.",
            authBottomSheetPlaybackSubtitle = "Playback, rewards, and account data require sign in.",
            authBottomSheetAccountSubtitle = "Sign in to view points, watch history, and orders.",
            authBrandSubtitle = "Aggregated short drama player",
            authClose = "Close",
            authUsernameLabel = "Phone number",
            authPasswordLabel = "Password",
            authLoginLoading = "Signing in",
            authLoginAction = "Sign in",
            authLoginSecondary = "Already have access? Sign in",
            authRegisterAction = "Create account",
            authRegisterSecondary = "New here? Create account",
            authSendCode = "Send code",
            authVerificationCodeLabel = "Verification code",
            authPromptPlayback = "Sign in to keep watching",
            authPromptAccount = "Sign in to view your account",
            rememberPassword = "Remember password",
            playerEpisodePrefix = "EP ",
            playerEpisodeUnit = "",
            playerPlayAction = "Play",
            playerLoadingPrefix = "Loading ",
            playerLoadingSuffix = "...",
            playerEpisodeSelectorPrefix = "Episodes",
            playerEpisodeSelectorCompleted = "Completed",
            playerEpisodeSelectorTotalPrefix = "Total ",
            playerEpisodeSelectorTotalSuffix = "",
            playerRefreshAction = "Refresh stream",
            playerRetryAction = "Retry",
            playerNextEpisodeAction = "Next episode",
            playerBackAction = "Back",
            playerRewardError = "Reward claim failed. You can keep watching.",
            playerVideoError = "Video failed to load. Please try again later.",
            playerFavoriteLabel = "Favorite",
            playerCurrentEpisodePrefix = "Current ",
            playerEpisodeStatusCurrent = "Current",
            playerEpisodeStatusWatched = "Watched",
            playerExpandEpisodes = "Open episode list",
            playerClose = "Close",
            playerCommentsTitlePrefix = "Comments ",
            playerCommentsEmpty = "No comments yet. Be the first one here.",
            playerCommentPlaceholder = "Write a comment…",
            playerSend = "Send",
            playerCommentUnit = "comments",
            listEpisodePrefix = "Episode ",
            listPointsChangeFallback = "Point update",
            listPointRecordSubtitle = "Point record",
            listCurrencySymbol = "$",
            listPointsLabel = "pts",
            accountFrozenAvailableLabel = "Frozen / available",
            accountWalletNoBound = "No wallet bound",
            accountWalletAddressLabel = "TRC20 wallet address",
            accountWalletUnbindCode = "Unbind code",
            accountWalletBindAction = "Bind wallet",
            accountWalletReplaceAction = "Replace wallet",
            accountWalletUnbindAction = "Unbind",
            accountWithdrawAvailableLabel = "Available",
            accountWithdrawMinimumLabel = "Min",
            accountWithdrawRateLabel = "1 pt",
            accountWithdrawWalletRequired = "Bind a cold wallet before withdrawal.",
            accountWithdrawPointAmountLabel = "Point amount",
            accountWithdrawSubmitAction = "Submit withdrawal",
            accountTransferHelp = "Use the recipient full phone account, for example +14155550101.",
            accountTransferRecipientLabel = "Recipient account",
            accountTransferPointsLabel = "Points",
            accountTransferInLabel = "Received",
            accountTransferOutLabel = "Sent",
            accountPasswordNewLabel = "New password",
            accountBankCardUnsupported = "Bank card withdrawal is not supported. This entry is reserved.",
            accountBankCardHolderLabel = "Holder name",
            accountBankCardNumberLabel = "Card number",
            commonNotSupported = "Not supported",
            posterEpisodeUnit = " eps",
            bookRowFallbackSuffix = " episodes",
            bookRowViewAction = "View",
        )
        AppLanguage.TRADITIONAL_CHINESE -> AppStrings(
            homeTab = "首頁",
            searchTab = "探索",
            accountTab = "我的",
            loginScreen = "登入",
            detailScreen = "詳情",
            playerScreen = "播放",
            favoritesScreen = "我的收藏",
            searchTitle = "探索內容",
            searchSubtitle = "從題材、角色或關鍵詞開始。",
            searchHint = "搜尋愛情、霸總、復仇...",
            searchAction = "搜尋",
            searchTagsTitle = "熱門方向",
            searchHeroEyebrow = "精選探索",
            searchResultTitle = "搜尋結果",
            searchResultCountSuffix = "部短劇",
            searchEmptyTitle = "發現短劇",
            searchInitialHint = "選擇預設標籤，或輸入短劇名稱。",
            searchEmpty = "沒有找到符合條件的短劇。",
            languageTitle = "語言",
            languageSubtitle = "English / 繁體中文",
            loadingDialogTitle = "正在載入",
            homeHeaderTitle = "今日推薦",
            homeHeaderSubtitleSuffix = "部短劇為你整理",
            favoritesHeaderTitle = "我的收藏",
            favoritesHeaderSubtitleSuffix = "部短劇已收藏",
            diagnosticsTitle = "開發診斷",
            diagnosticsExpand = "查看",
            diagnosticsCollapse = "收起",
            diagnosticsRefresh = "刷新診斷",
            diagnosticsApiMissing = "API 位址未配置",
            diagnosticsUnknownLabel = "未檢測",
            diagnosticsUnknownMessage = "點擊刷新，檢查模擬器是否能訪問 Spring Boot。",
            diagnosticsUpLabel = "已連線",
            diagnosticsUpMessagePrefix = "後端 ",
            diagnosticsDownLabel = "連線異常",
            diagnosticsDownMessagePrefix = "後端健康狀態為 ",
            homeEmptyTitle = "今日暫無推薦",
            homeEmptyMessage = "內容源暫時沒有返回推薦短劇，可以先搜尋片名或關鍵詞。",
            homeEmptyAction = "去搜尋",
            favoritesEmptyTitle = "還沒有收藏",
            favoritesEmptyMessage = "在播放頁點擊收藏，喜歡的短劇會出現在這裡。",
            searchDefaultEmptyTitle = "發現短劇",
            searchDefaultEmptyMessage = "輸入劇名、角色或關鍵詞，快速找到想看的短劇。",
            searchNoResultsTitle = "沒有找到相關短劇",
            searchNoResultsMessagePrefix = "沒有匹配“",
            searchNoResultsMessageSuffix = "”的內容，換個關鍵詞再試。",
            searchRetryAction = "重新搜尋",
            detailEmptyTitle = "先選擇一部短劇",
            detailEmptyMessage = "從首頁推薦或搜尋結果進入詳情後，這裡會展示分集列表。",
            detailEmptyAction = "返回首頁",
            detailUnavailableTitle = "分集暫不可用",
            detailUnavailableMessagePrefix = "“",
            detailUnavailableMessageSuffix = "”暫時沒有可播放分集，可以稍後刷新或選擇其他短劇。",
            detailUnavailableAction = "換一部",
            accountFavoritesTitle = "我的收藏",
            accountPointsTitle = "積分餘額",
            accountWatchHistoryTitle = "觀看記錄",
            accountPointRecordsTitle = "積分流水",
            accountOrdersTitle = "充值訂單",
            accountWalletTitle = "冷錢包",
            accountWithdrawTitle = "提現",
            accountTransferTitle = "積分交易",
            accountTransferRecordsTitle = "交易記錄",
            accountChangePasswordTitle = "修改密碼",
            accountBankCardTitle = "銀行卡",
            accountWithdrawalsTitle = "提現記錄",
            accountDiagnosticsTitle = "開發診斷",
            accountSignOutTitle = "退出登入",
            accountGuestSignIn = "登入",
            accountGuestRegister = "註冊",
            accountGuestSignInSubtitle = "登入後可播放短劇並獲取積分",
            accountGuestRegisterSubtitle = "建立帳號保存觀看進度",
            accountFavoritesSubtitle = "收藏的短劇",
            accountViewAction = "查看",
            accountPointsSuffix = " 積分",
            accountRecentCountPrefix = "最近 ",
            accountRecordsSuffix = " 條",
            accountOrdersReserved = "商業化預留",
            accountOrdersRecentSuffix = " 筆",
            accountRecentWatchTitle = "最近觀看",
            accountRecentWatchSubtitle = "繼續上次的短劇進度",
            accountSelectedLanguage = "已選擇",
            accountUserFallback = "ShortLink 用戶",
            accountGuestUser = "遊客",
            accountLoggedInStatus = "已登入 · ShortLink",
            accountGuestStatus = "登入後可保存觀看進度和積分",
            accountPointsPillPrefix = "積分 ",
            accountGuestPill = "未登入",
            accountLoggedInRewardHint = "持續觀看可獲得獎勵",
            accountGuestRewardHint = "可先瀏覽首頁和搜尋",
            accountSignOutSubtitle = "退出當前帳號",
            accountSignInSuccessHint = "已登入",
            authLoginTitle = "歡迎回來",
            authLoginSubtitle = "使用手機帳號登入後繼續觀看。",
            authRegisterTitle = "建立帳號",
            authRegisterSubtitle = "請使用非中國大陸手機號，並輸入 6 位數驗證碼。",
            authBottomSheetPlaybackSubtitle = "播放、積分和帳戶資料需要登入帳號。",
            authBottomSheetAccountSubtitle = "登入後可以查看積分、觀看記錄和訂單。",
            authBrandSubtitle = "聚合短劇播放平台",
            authClose = "關閉",
            authUsernameLabel = "手機號",
            authPasswordLabel = "密碼",
            authLoginLoading = "登入中",
            authLoginAction = "登入",
            authLoginSecondary = "已有帳號？立即登入",
            authRegisterAction = "註冊",
            authRegisterSecondary = "還沒有帳號？立即建立",
            authSendCode = "發送驗證碼",
            authVerificationCodeLabel = "驗證碼",
            authPromptPlayback = "登入後繼續播放",
            authPromptAccount = "登入後查看帳戶",
            rememberPassword = "記住密碼",
            playerEpisodePrefix = "第 ",
            playerEpisodeUnit = " 集",
            playerPlayAction = "播放",
            playerLoadingPrefix = "載入",
            playerLoadingSuffix = "...",
            playerEpisodeSelectorPrefix = "選集",
            playerEpisodeSelectorCompleted = "已完結",
            playerEpisodeSelectorTotalPrefix = "全",
            playerEpisodeSelectorTotalSuffix = "集",
            playerRefreshAction = "刷新地址",
            playerRetryAction = "重試",
            playerNextEpisodeAction = "下一集",
            playerBackAction = "返回",
            playerRewardError = "獎勵領取失敗，可繼續觀看",
            playerVideoError = "影片載入失敗，請稍後重試",
            playerFavoriteLabel = "收藏",
            playerCurrentEpisodePrefix = "當前 ",
            playerEpisodeStatusCurrent = "目前",
            playerEpisodeStatusWatched = "已看",
            playerExpandEpisodes = "展開選集",
            playerClose = "關閉",
            playerCommentsTitlePrefix = "評論 ",
            playerCommentsEmpty = "還沒有評論，快來搶沙發吧",
            playerCommentPlaceholder = "寫下你的評論…",
            playerSend = "發送",
            playerCommentUnit = "條評論",
            listEpisodePrefix = "第 ",
            listPointsChangeFallback = "積分變動",
            listPointRecordSubtitle = "積分流水",
            listCurrencySymbol = "¥",
            listPointsLabel = "積分",
            accountFrozenAvailableLabel = "凍結 / 可用",
            accountWalletNoBound = "未綁定冷錢包",
            accountWalletAddressLabel = "TRC20 錢包地址",
            accountWalletUnbindCode = "解綁驗證碼",
            accountWalletBindAction = "綁定錢包",
            accountWalletReplaceAction = "更換錢包",
            accountWalletUnbindAction = "解綁",
            accountWithdrawAvailableLabel = "可用",
            accountWithdrawMinimumLabel = "最低",
            accountWithdrawRateLabel = "1 積分",
            accountWithdrawWalletRequired = "提現前需要先綁定冷錢包。",
            accountWithdrawPointAmountLabel = "提現積分",
            accountWithdrawSubmitAction = "提交提現",
            accountTransferHelp = "請填寫對方完整手機帳號，例如 +14155550101。",
            accountTransferRecipientLabel = "對方帳號",
            accountTransferPointsLabel = "交易積分",
            accountTransferInLabel = "轉入",
            accountTransferOutLabel = "轉出",
            accountPasswordNewLabel = "新密碼",
            accountBankCardUnsupported = "暫不支持銀行卡提現，此入口僅作預留。",
            accountBankCardHolderLabel = "持卡人姓名",
            accountBankCardNumberLabel = "銀行卡號",
            commonNotSupported = "暫不支持",
            posterEpisodeUnit = " 集",
            bookRowFallbackSuffix = " 集短劇",
            bookRowViewAction = "查看",
        )
    }

internal fun searchDiscoveryTags(language: AppLanguage): List<String> =
    searchDiscoveryGroups(language).flatMap { it.tags }

internal data class SearchDiscoveryGroup(
    val title: String,
    val tags: List<String>,
)

internal fun searchDiscoveryGroups(language: AppLanguage): List<SearchDiscoveryGroup> =
    when (language) {
        AppLanguage.ENGLISH -> listOf(
            SearchDiscoveryGroup("Story moods", listOf("Love", "Revenge", "Secret", "Family")),
            SearchDiscoveryGroup("Power roles", listOf("Billionaire", "CEO", "Boss", "Queen", "Doctor")),
            SearchDiscoveryGroup("Relationships", listOf("Marriage", "Contract", "Pregnant")),
            SearchDiscoveryGroup("Fantasy heat", listOf("Mafia", "Werewolf", "Alpha", "Luna")),
        )
        AppLanguage.TRADITIONAL_CHINESE -> listOf(
            SearchDiscoveryGroup("故事情緒", listOf("愛情", "復仇", "秘密", "家庭")),
            SearchDiscoveryGroup("強勢角色", listOf("億萬富翁", "霸總", "老闆", "女王", "醫生")),
            SearchDiscoveryGroup("關係張力", listOf("婚姻", "契約", "懷孕")),
            SearchDiscoveryGroup("幻想熱點", listOf("黑幫", "狼人", "Alpha", "Luna")),
        )
    }

internal fun searchShowsResultsFirst(query: String, resultCount: Int): Boolean =
    query.isNotBlank() || resultCount > 0
