spring.application.name=reelshort-backend
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
reelshort.content-provider.base-url=http://127.0.0.1:5000
spring.http.client.connect-timeout=2s
spring.http.client.read-timeout=5s
