spring.datasource.url=jdbc:h2:file:./data/app-dev/reelshort;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
reelshort.rate-limit.enabled=false
reelshort.content-provider.base-url=http://127.0.0.1:5000
reelshort.auth.session.cleanup-initial-delay=24h
reelshort.admin.session.cleanup-initial-delay=24h
